#!/bin/bash

echo ""
echo "========== Compiling executable $1 =========="

echo ""
echo "========== Performing safety checks =========="

if [ "$#" -ne 0 ]; then
    echo "Wrong number of arguments"
    echo "  Syntax is ./BuildExec"
    exit 1
else
    echo "Correct number of arguments"
fi

echo ""
echo "========== Generating build directory =========="
cmake src/CMakeLists.txt -Bbuild

echo ""
echo "========== Compiling from build directory =========="
cd build/
make $1
cd ..

echo ""
echo "========== Executable $1 built =========="
date
echo ""
exit 0
